version: "3.6"

services:
  app:
    build: ./infra/php
    volumes:
      - ./app:/work
    env_file:
      - .env

  web:
    image: nginx:1.18-alpine
    ports:
      - 10082:80
    volumes:
      - ./app:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    ports:
      - 33063:3306
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: